#region Header

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#endregion Header

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Modules.Acl.Core")]
[assembly: AssemblyDescription("The core module for the Adgistics Acl Modules.")]
[assembly: AssemblyCompany("http://www.adgistics.com")]
[assembly: AssemblyProduct("Modules.Acl")]
[assembly: AssemblyCopyright("Copyright (c) 2015 Adgistics Limited")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("0.0.1.1435")]
[assembly: AssemblyFileVersion("0.0.1.0122")]
[assembly: AssemblyInformationalVersion("0.0.1.1435")]