//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Modules.Acl-Test")]
[assembly: AssemblyDescription("The test library for the Adgistics Acl Modules.")]
[assembly: AssemblyCompany("http://www.adgistics.com")]
[assembly: AssemblyProduct("Modules.Acl")]
[assembly: AssemblyCopyright("Copyright (c) 2015 Adgistics Limited")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("1.0.0.28")]
[assembly: AssemblyFileVersion("1.0.0.0122")]
[assembly: AssemblyInformationalVersion("1.0.0.28")]


